"use client";
import { Suspense, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { PayPalScriptProvider, PayPalButtons, PayPalCardFieldsProvider, PayPalCardFieldsForm, usePayPalCardFields, PayPalHostedFieldsProvider } from "@paypal/react-paypal-js";
import { api } from "@/lib/api";
import { useStore } from "@/lib/store";
import { Button, Field, fmt } from "@/components/ui";

export default function Page() { return <Suspense><Checkout /></Suspense>; }
function Checkout() {
  const sp = useSearchParams(); const router = useRouter(); const qc = useQueryClient(); const { toast, openSheet, closeSheet, setCredits, user } = useStore();
  const planKey = sp.get("plan") ?? undefined, packKey = sp.get("pack") ?? undefined;
  const cat = useQuery({ queryKey: ["catalog"], queryFn: () => api("/billing/catalog") }); const bill = useQuery({ queryKey: ["billing"], queryFn: () => api("/billing") });
  const item = planKey ? cat.data?.plans.find((p: any) => p.key === planKey) : cat.data?.packs.find((p: any) => p.key === packKey);
  const [coupon, setCoupon] = useState(""); const [applied, setApplied] = useState<any>(null); const [pm, setPm] = useState<string>("new"); const [saveCard, setSaveCard] = useState(true); const [addr, setAddr] = useState({ name: user?.name ?? "", company: "", street: "", city: "", country: "" });
  if (!item) return <div className="page"><div className="card">Loading…</div></div>;
  const base = item.priceCents; const amount = applied?.pctOff ? Math.round(base * (100 - applied.pctOff) / 100) : base;
  const createOrder = async () => (await api("/billing/orders", { method: "POST", json: { planKey, packKey, coupon: applied?.code, saveCard } })).orderId;
  const onApprove = async (data: { orderID: string }) => { try { const r = await api(`/billing/orders/${data.orderID}/capture`, { method: "POST", json: { planKey, packKey, coupon: applied?.code } }); const b = await api("/billing"); setCredits(b.credits); qc.invalidateQueries({ queryKey: ["billing"] });
      openSheet(<div style={{ textAlign: "center", padding: 10 }}><div style={{ fontSize: 48 }}>✓</div><h2 style={{ fontSize: 22 }}>{planKey ? `You're on ${item.name}` : "Credits added"}</h2><p className="sub"><b>{fmt(r.credits)}</b> credits landed. Receipt {r.invoice} is in your inbox.</p><Button variant="primary" size="lg" onClick={() => { closeSheet(); router.push("/"); }}>Start building</Button></div>); } catch (e: any) { toast(e.message); } };
  const savedTopup = async (packKeyOrPlan: string) => { try { if (packKey) { const r = await api("/billing/topup", { method: "POST", json: { packKey } }); setCredits(r.balance); toast(`${fmt(r.credits)} credits added`); router.push("/"); } else toast("Use the card form below for a new plan; saved-card checkout applies to packs."); } catch (e: any) { toast(e.message); } };
  return <PayPalScriptProvider options={{ clientId: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID!, components: "buttons,card-fields,googlepay", currency: "USD", intent: "capture", vault: saveCard }}>
    <div className="page"><div className="checkout"><div>
      <h1 style={{ fontSize: 24, marginBottom: 16 }}>Payment</h1>
      <div className="card"><div className="paym">{(bill.data?.paymentMethods ?? []).map((c: any) => <div key={c.id} className={`pm ${pm === c.id ? "on" : ""}`} onClick={() => setPm(c.id)}><span className="cb" /><span className="cardbrand">{c.brand ?? c.provider}</span><span>•••• {c.last4}</span><span className="muted">{c.expMonth}/{String(c.expYear).slice(-2)}</span>{c.isDefault && <span className="tag" style={{ marginLeft: "auto" }}>Default</span>}</div>)}<div className={`pm ${pm === "new" ? "on" : ""}`} onClick={() => setPm("new")}><span className="cb" />Add a new card</div></div>
        {pm !== "new" ? <Button variant="primary" size="lg" style={{ width: "100%", marginTop: 14 }} onClick={() => savedTopup(pm)}>Pay ${(amount / 100).toFixed(2)} with saved card</Button> :
        <PayPalCardFieldsProvider createOrder={createOrder} onApprove={onApprove} onError={() => toast("Your bank declined this card. Try another card or PayPal.")} style={{ input: { "font-size": "14px", "font-family": "Inter, sans-serif", padding: "10px 12px", color: "#14121F" } }}>
          <div style={{ marginTop: 14 }}><PayPalCardFieldsForm /><label className="row" style={{ gap: 10, fontSize: 13, marginTop: 8 }}><input type="checkbox" checked={saveCard} onChange={(e) => setSaveCard(e.target.checked)} /> Save this card for renewals and one-tap credit top-ups</label><SubmitCard amount={amount} /></div></PayPalCardFieldsProvider>}
        <hr className="sep" /><PayPalButtons style={{ layout: "horizontal", height: 44, tagline: false }} fundingSource={undefined} createOrder={createOrder} onApprove={onApprove as any} />
        <p className="lock" style={{ margin: "12px 0 0" }}>🔒 Card details are handled by PayPal's secure fields inside this page. Purpio never sees your card number.</p></div>
      <div className="card" style={{ marginTop: 16 }}><h3 style={{ fontSize: 15, marginBottom: 10 }}>Billing address</h3><div className="grid g2"><Field label="Full name"><input className="input" autoComplete="name" value={addr.name} onChange={(e) => setAddr({ ...addr, name: e.target.value })} /></Field><Field label="Company (optional)"><input className="input" autoComplete="organization" value={addr.company} onChange={(e) => setAddr({ ...addr, company: e.target.value })} /></Field><div style={{ gridColumn: "1/-1" }}><Field label="Street address"><input className="input" autoComplete="street-address" value={addr.street} onChange={(e) => setAddr({ ...addr, street: e.target.value })} /></Field></div><Field label="City"><input className="input" autoComplete="address-level2" value={addr.city} onChange={(e) => setAddr({ ...addr, city: e.target.value })} /></Field><Field label="Country"><input className="input" autoComplete="country-name" value={addr.country} onChange={(e) => setAddr({ ...addr, country: e.target.value })} onBlur={() => api("/billing/details", { method: "PATCH", json: { company: addr.company, address: `${addr.street}, ${addr.city}, ${addr.country}` } }).catch(() => {})} /></Field></div></div></div>
      <div className="card" style={{ position: "sticky", top: 80 }}><h3 style={{ fontSize: 15 }}>Order summary</h3><div className="row" style={{ justifyContent: "space-between", marginTop: 12 }}><span>{item.name}{planKey ? " plan, monthly" : ""}</span><b>${(base / 100).toFixed(2)}</b></div><div className="muted" style={{ marginTop: 6 }}>{fmt(item.creditsPerPeriod ?? item.credits)} credits{planKey ? " every month" : ""}</div>{applied && <div className="row" style={{ justifyContent: "space-between", marginTop: 6, color: "var(--ok)" }}><span>{applied.code}</span><span>−${((base - amount) / 100).toFixed(2)}</span></div>}
        <div className="field" style={{ marginTop: 12 }}><div className="row"><input className="input" placeholder="Coupon code" value={coupon} onChange={(e) => setCoupon(e.target.value)} style={{ flex: 1 }} /><Button size="sm" onClick={async () => { try { setApplied(await api("/billing/coupon", { method: "POST", json: { code: coupon } })); toast("Coupon applied"); } catch (e: any) { toast(e.message); } }}>Apply</Button></div></div>
        <hr className="sep" /><div className="row" style={{ justifyContent: "space-between" }}><b>Due today</b><b style={{ fontSize: 20 }}>${(amount / 100).toFixed(2)}</b></div>{planKey && <p className="muted" style={{ fontSize: 12 }}>Renews in one month at ${(base / 100).toFixed(2)}. Auto-renew is on; turn it off any time in Billing.</p>}</div></div></div></PayPalScriptProvider>;
}
function SubmitCard({ amount }: { amount: number }) { const { cardFieldsForm } = usePayPalCardFields(); const [busy, setBusy] = useState(false);
  return <Button variant="primary" size="lg" style={{ width: "100%", marginTop: 12 }} loading={busy} onClick={async () => { if (!cardFieldsForm) return; setBusy(true); try { const s = await cardFieldsForm.getState(); if (!s.isFormValid) { setBusy(false); return; } await cardFieldsForm.submit(); } finally { setBusy(false); } }}>Pay ${(amount / 100).toFixed(2)} now</Button>; }
