"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { useStore } from "@/lib/store";
import { Button, Field, Switch, Tag, fmt } from "@/components/ui";
import { TopupSheet } from "@/components/TopupSheet";
import { signOut } from "firebase/auth";
import { auth } from "@/lib/firebase";

const MENU: [string, [string, string][]][] = [["General", [["profile", "Profile"], ["appearance", "Appearance"], ["models", "Models & defaults"], ["notifications", "Notifications"]]], ["Plan", [["usage", "Usage"], ["billing", "Billing"], ["invoices", "Invoices"], ["referrals", "Referrals"]]], ["Developer", [["connections", "Connections"], ["secrets", "Secrets"], ["api", "API keys"], ["team", "Team"]]], ["Account", [["security", "Security"]]]];

export default function Settings({ params }: { params: { section?: string[] } }) {
  const sec = params.section?.[0] ?? "profile"; const S = SECTIONS[sec] ?? SECTIONS.profile;
  return <div className="page"><div className="settings"><nav className="smenu">{MENU.map(([g, items]) => <div key={g}><span className="grp">{g}</span>{items.map(([k, l]) => <Link key={k} href={`/settings/${k}`} className={k === sec ? "on" : ""}>{l}</Link>)}</div>)}</nav><div><S /></div></div></div>;
}
function useSaved() { const [s, setS] = useState(false); return { saved: s, flash: () => { setS(true); setTimeout(() => setS(false), 1500); }, Tag: () => <span className={`saved ${s ? "show" : ""}`}>Saved</span> }; }
function usePatch() { const { setUser, toast } = useStore(); return async (d: any) => { try { const r = await api("/account", { method: "PATCH", json: d }); setUser(r.user); return true; } catch (e: any) { toast(e.message); return false; } }; }

const SECTIONS: Record<string, () => JSX.Element> = {
  profile: () => { const { user } = useStore(); const patch = usePatch(); const sv = useSaved(); const [f, setF] = useState({ name: user?.name ?? "", locale: user?.locale ?? "en", timezone: user?.timezone ?? "UTC" });
    const save = async () => { if (await patch(f)) sv.flash(); };
    return <div className="card"><div className="row" style={{ justifyContent: "space-between" }}><h2 className="h-sec" style={{ margin: 0 }}>Profile</h2><sv.Tag /></div><hr className="sep" /><div className="grid g2"><Field label="Name"><input className="input" autoComplete="name" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} onBlur={save} /></Field><Field label="Email" hint="Changing it sends a verification link to the new address."><input className="input" autoComplete="email" value={user?.email ?? ""} readOnly /></Field><Field label="Language"><select className="input" value={f.locale} onChange={(e) => { setF({ ...f, locale: e.target.value }); }} onBlur={save}><option value="en">English</option><option value="ar">العربية</option><option value="es">Español</option><option value="fr">Français</option></select></Field><Field label="Timezone"><input className="input" value={f.timezone} onChange={(e) => setF({ ...f, timezone: e.target.value })} onBlur={save} /></Field></div></div>; },
  appearance: () => { const { theme, setTheme, toast } = useStore(); const patch = usePatch(); const { user } = useStore(); const rm = !!user?.prefs?.reduceMotion;
    return <div className="card"><h2 className="h-sec">Appearance</h2><hr className="sep" /><div className="grid g3">{(["light", "dark", "system"] as const).map((t) => <button key={t} className="card flat" style={{ cursor: "pointer", textAlign: "left", borderColor: theme === t ? "var(--brand)" : undefined }} onClick={() => setTheme(t)}><div style={{ height: 60, borderRadius: 8, background: t === "dark" ? "#15131F" : t === "light" ? "#fff" : "linear-gradient(90deg,#fff 50%,#15131F 50%)", border: "1px solid var(--line)", marginBottom: 8 }} /><b>{t[0].toUpperCase() + t.slice(1)}</b></button>)}</div><hr className="sep" /><label className="row" style={{ justifyContent: "space-between" }}><span><b>Reduce motion</b><br /><span className="hint">Turns off the 3D hero and animations.</span></span><Switch on={rm} onChange={async (v) => { await patch({ prefs: { reduceMotion: v } }); toast("Saved"); }} /></label></div>; },
  models: () => { const { data } = useQuery({ queryKey: ["models"], queryFn: () => api("/models") }); const { user, toast } = useStore(); const patch = usePatch();
    return <div className="card"><h2 className="h-sec">Models & defaults</h2><p className="muted" style={{ margin: "0 0 12px" }}>Each model charges credits at its own rate. The estimate before every run uses the model you pick.</p><table className="t"><thead><tr><th>Model</th><th>Best for</th><th>Credit rate</th><th>Default</th></tr></thead><tbody>{(data ?? []).map((m: any) => <tr key={m.key}><td><b>{m.label}</b> {m.locked && <Tag kind="brand">Pro</Tag>}</td><td className="muted">{m.description}</td><td>{m.multiplier != null ? `${m.multiplier}× base` : m.creditsPerImage ? `${m.creditsPerImage} / image` : `${m.creditsPerVideoS} / second`}</td><td>{m.multiplier != null && <input type="radio" name="dm" checked={user?.defaultModel === m.key} disabled={m.locked} onChange={async () => { await patch({ defaultModel: m.key }); toast(`Default model: ${m.label}`); }} />}</td></tr>)}</tbody></table></div>; },
  notifications: () => { const { user, toast } = useStore(); const patch = usePatch(); const prefs = user?.prefs?.notify ?? {}; const EV = [["build", "Build finished while away"], ["deploy", "Deploy finished or failed"], ["credits", "Credits at 20% and 0"], ["billing", "Receipts and renewals"], ["team", "Team invites and comments"], ["product", "Product updates (monthly)"]];
    const set = async (k: string, ch: "email" | "app", v: boolean) => { await patch({ prefs: { notify: { ...prefs, [k]: { ...(prefs[k] ?? { email: true, app: true }), [ch]: v } } } }); toast("Saved"); };
    return <div className="card"><h2 className="h-sec">Notifications</h2><table className="t"><thead><tr><th>Event</th><th>Email</th><th>In app</th></tr></thead><tbody>{EV.map(([k, l]) => <tr key={k}><td>{l}</td><td><Switch on={prefs[k]?.email ?? k !== "product"} onChange={(v) => set(k, "email", v)} /></td><td><Switch on={prefs[k]?.app ?? true} onChange={(v) => set(k, "app", v)} /></td></tr>)}</tbody></table></div>; },
  usage: () => { const { data } = useQuery({ queryKey: ["usage"], queryFn: () => api("/billing/usage") }); const bill = useQuery({ queryKey: ["billing"], queryFn: () => api("/billing") }); const { openSheet } = useStore();
    if (!data) return <div className="card">Loading…</div>; const max = bill.data?.subscription?.plan?.creditsPerPeriod ?? 150; const pct = Math.max(0, Math.min(1, data.balance.available / max)); const C = 2 * Math.PI * 52;
    const days = Array.from({ length: 30 }, (_, i) => { const d = new Date(Date.now() - (29 - i) * 864e5).toISOString().slice(0, 10); return [d, data.byDay[d] ?? 0] as const; }); const mx = Math.max(1, ...days.map((d) => d[1]));
    return <><div className="grid g2"><div className="card"><h2 className="h-sec">Credits</h2><div className="row" style={{ gap: 22 }}><div className="ring"><svg width="120" height="120"><defs><linearGradient id="rg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#8B5CF6" /><stop offset="1" stopColor="#4F46E5" /></linearGradient></defs><circle className="c" cx="60" cy="60" r="52" /><circle className="v" cx="60" cy="60" r="52" strokeDasharray={C} strokeDashoffset={C * (1 - pct)} /></svg><div className="lbl"><div><b>{fmt(data.balance.available)}</b><br /><small>of {fmt(max)}</small></div></div></div><div><b>{Math.round(pct * 100)}% left</b><p className="muted" style={{ margin: "4px 0 10px" }}>{data.balance.held ? `${fmt(data.balance.held)} reserved for running jobs` : "Nothing running"}</p><Button size="sm" variant="primary" onClick={() => openSheet(<TopupSheet />)}>Buy credits</Button></div></div></div>
      <div className="card"><h2 className="h-sec">By model, 30 days</h2><table className="t"><tbody>{data.byModel.map((m: any) => <tr key={m.modelKey}><td>{m.modelKey ?? "—"}</td><td style={{ textAlign: "right" }}><b>{fmt(m._sum.creditsUsed ?? 0)}</b></td></tr>)}</tbody></table></div></div>
      <div className="card" style={{ marginTop: 16 }}><div className="row" style={{ justifyContent: "space-between" }}><h2 className="h-sec" style={{ margin: 0 }}>Daily spend, last 30 days</h2><Button size="sm" onClick={() => { const csv = "date,credits\n" + days.map((d) => d.join(",")).join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); a.download = "purpio-usage.csv"; a.click(); }}>Export CSV</Button></div><div className="bars" style={{ marginTop: 18 }}>{days.map(([d, v]) => <i key={d} style={{ height: `${(v / mx) * 100}%` }} data-v={v} title={`${d}: ${v}`} />)}</div><div className="row" style={{ justifyContent: "space-between", marginTop: 6 }}><small className="muted">{days[0][0]}</small><small className="muted">Total {fmt(days.reduce((a, d) => a + d[1], 0))} credits</small><small className="muted">{days[29][0]}</small></div></div></>; },
  billing: () => { const qc = useQueryClient(); const { data } = useQuery({ queryKey: ["billing"], queryFn: () => api("/billing") }); const cat = useQuery({ queryKey: ["catalog"], queryFn: () => api("/billing/catalog") }); const { toast, openSheet, closeSheet, user } = useStore(); const router = useRouter(); const sv = useSaved(); const [det, setDet] = useState({ company: user?.prefs?.company ?? "", vat: user?.prefs?.vat ?? "" });
    if (!data) return <div className="card">Loading…</div>; const sub = data.subscription; const patchSub = async (d: any) => { await api("/billing/subscription", { method: "PATCH", json: d }); qc.invalidateQueries({ queryKey: ["billing"] }); };
    return <><div className="card"><div className="row" style={{ justifyContent: "space-between" }}><div><h2 className="h-sec" style={{ margin: 0 }}>{sub?.plan?.name ?? "Free"} plan <Tag kind={sub?.status === "past_due" ? "bad" : sub?.status === "paused" ? "warn" : "ok"}>{sub?.status ?? "active"}</Tag></h2><p className="muted" style={{ margin: "4px 0 0" }}>{fmt(sub?.plan?.creditsPerPeriod ?? 150)} credits a month · {sub?.cancelAtPeriodEnd ? "ends" : "next charge"} {new Date(sub?.currentPeriodEnd).toLocaleDateString()}</p></div><div className="row"><Link className="btn" href="/pricing">Change plan</Link>{sub?.planKey !== "free" && <Button variant="ghost" className="danger" onClick={() => openSheet(<><h2 style={{ fontSize: 20 }}>Cancel at period end?</h2><p className="sub">You keep every project and the source code. Credits stay usable until {new Date(sub.currentPeriodEnd).toLocaleDateString()}. You can also pause for 1 to 3 months.</p><div className="row" style={{ justifyContent: "flex-end" }}><Button variant="ghost" onClick={closeSheet}>Keep plan</Button><Button onClick={async () => { await patchSub({ pauseMonths: 1 }); closeSheet(); toast("Paused for 1 month"); }}>Pause 1 month</Button><Button variant="danger" onClick={async () => { await patchSub({ cancelAtPeriodEnd: true }); closeSheet(); toast("Plan ends at period end"); }}>Cancel</Button></div></>)}>Cancel</Button>}</div></div>
      {sub?.planKey !== "free" && <><hr className="sep" /><label className="row" style={{ justifyContent: "space-between" }}><span><b>Auto-renew</b><br /><span className="hint">Charges your default card on the renewal date. We email you 3 days before.</span></span><Switch on={!!sub?.autoRenew} onChange={async (v) => { await patchSub({ autoRenew: v }); toast(v ? "Auto-renew on" : "Auto-renew off"); }} /></label></>}</div>
      <div className="card" style={{ marginTop: 16 }}><div className="row" style={{ justifyContent: "space-between" }}><h2 className="h-sec" style={{ margin: 0 }}>Payment methods</h2><Link className="btn sm" href="/checkout?pack=p800">Add card</Link></div><div className="paym" style={{ marginTop: 12 }}>{data.paymentMethods.map((c: any) => <div key={c.id} className="pm" style={{ cursor: "default" }}><span className="cardbrand">{c.brand ?? c.provider}</span><span>•••• {c.last4}</span><span className="muted">{c.expMonth}/{String(c.expYear).slice(-2)}</span>{c.isDefault && <span className="tag">Default</span>}<span style={{ marginLeft: "auto" }} className="row">{!c.isDefault && <Button size="sm" variant="ghost" onClick={async () => { await api(`/billing/payment-methods/${c.id}`, { method: "PATCH" }); qc.invalidateQueries({ queryKey: ["billing"] }); }}>Set default</Button>}<Button size="sm" variant="ghost" className="danger" onClick={async () => { await api(`/billing/payment-methods/${c.id}`, { method: "DELETE" }); qc.invalidateQueries({ queryKey: ["billing"] }); toast("Card removed"); }}>Remove</Button></span></div>)}{!data.paymentMethods.length && <p className="muted">No saved cards yet. One is saved when you pay with a card.</p>}</div><p className="lock" style={{ margin: "12px 0 0" }}>🔒 Stored as PayPal vault tokens. Card numbers never touch Purpio.</p></div>
      <div className="card" style={{ marginTop: 16 }}><h2 className="h-sec">Credit packs</h2><div className="grid g4">{(cat.data?.packs ?? []).map((p: any) => <button key={p.key} className="card flat" style={{ cursor: "pointer", textAlign: "left" }} onClick={() => data.paymentMethods.length ? openSheet(<TopupSheet />) : router.push(`/checkout?pack=${p.key}`)}><div className="row" style={{ justifyContent: "space-between" }}><b>{fmt(p.credits)}</b>{p.bonusPct ? <span className="tag brand">+{p.bonusPct}%</span> : null}</div><div className="muted">${p.priceCents / 100}</div></button>)}</div></div>
      <div className="card" style={{ marginTop: 16 }}><div className="row" style={{ justifyContent: "space-between" }}><h2 className="h-sec" style={{ margin: 0 }}>Invoice details</h2><sv.Tag /></div><div className="grid g2" style={{ marginTop: 12 }}><Field label="Company name"><input className="input" autoComplete="organization" value={det.company} onChange={(e) => setDet({ ...det, company: e.target.value })} onBlur={async () => { await api("/billing/details", { method: "PATCH", json: det }); sv.flash(); }} /></Field><Field label="VAT / Tax ID"><input className="input" value={det.vat} onChange={(e) => setDet({ ...det, vat: e.target.value })} onBlur={async () => { await api("/billing/details", { method: "PATCH", json: det }); sv.flash(); }} /></Field></div></div></>; },
  invoices: () => { const { data } = useQuery({ queryKey: ["billing"], queryFn: () => api("/billing") }); const { toast } = useStore();
    return <div className="card"><h2 className="h-sec">Invoices</h2><table className="t"><thead><tr><th>Number</th><th>Date</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{(data?.invoices ?? []).map((i: any) => <tr key={i.id}><td><b>{i.number}</b></td><td>{new Date(i.createdAt).toLocaleDateString()}</td><td>${(i.amountCents / 100).toFixed(2)}</td><td><Tag kind={i.status === "paid" ? "ok" : i.status === "refunded" ? "warn" : undefined}>{i.status}</Tag></td><td style={{ textAlign: "right" }}>{i.pdfUrl && <a className="btn sm" href={i.pdfUrl} target="_blank" rel="noreferrer">PDF</a>} <Button size="sm" variant="ghost" onClick={async () => { await api(`/billing/invoices/${i.id}/resend`, { method: "POST" }); toast("Receipt emailed"); }}>Email</Button></td></tr>)}{!data?.invoices?.length && <tr><td colSpan={5} className="muted">No invoices yet.</td></tr>}</tbody></table></div>; },
  referrals: () => { const { data } = useQuery({ queryKey: ["referrals"], queryFn: () => api("/referrals") }); const { toast } = useStore(); if (!data) return <div className="card">Loading…</div>;
    return <div className="card"><h2 className="h-sec">Referrals</h2><p className="sub">You and your friend both get 200 credits when they buy any plan.</p><div className="row"><input className="input" readOnly value={data.link} /><Button variant="primary" onClick={() => { navigator.clipboard.writeText(data.link); toast("Link copied"); }}>Copy</Button></div><hr className="sep" /><div className="grid g3"><div className="kpi"><b>{data.joined}</b><small>Friends joined</small></div><div className="kpi"><b>{data.credits}</b><small>Credits earned</small></div><div className="kpi"><b>{data.joined - data.rewarded}</b><small>Pending</small></div></div></div>; },
  connections: () => { const qc = useQueryClient(); const { data } = useQuery({ queryKey: ["connections"], queryFn: () => api("/connections") }); const { toast, openSheet, closeSheet } = useStore(); const DESC: Record<string, [string, string]> = { HOSTINGER_API_TOKEN: ["Hostinger", "Deploy to your own hosting"], GITHUB_TOKEN: ["GitHub", "Push source code to a repo"], GOOGLE_DRIVE_TOKEN: ["Google Drive", "Import brand files and references"], FIREBASE_SERVICE_ACCOUNT: ["Firebase", "Use your own auth and database"] };
    const connect = (name: string) => openSheet(<ConnectForm name={name} label={DESC[name][0]} onDone={() => { closeSheet(); qc.invalidateQueries({ queryKey: ["connections"] }); toast(`${DESC[name][0]} connected`); }} />);
    return <div className="card"><h2 className="h-sec">Connections</h2>{(data ?? []).map((c: any) => <div key={c.name} className="pm" style={{ cursor: "default" }}><div><b>{DESC[c.name][0]}</b><br /><small className="muted">{DESC[c.name][1]}</small></div><span style={{ marginLeft: "auto" }} className="row">{c.connected ? <><span className="secret">••••{c.last4}</span><span className="lock">🔒 Encrypted</span><Button size="sm" variant="ghost" onClick={() => connect(c.name)}>Rotate</Button></> : <Button size="sm" onClick={() => connect(c.name)}>Connect</Button>}</span></div>)}<p className="lock" style={{ marginTop: 10 }}>Tokens are encrypted with AES-256-GCM and a key Purpio staff cannot read. They are shown once, then only the last 4 characters.</p></div>; },
  secrets: () => { const qc = useQueryClient(); const { data } = useQuery({ queryKey: ["secrets"], queryFn: () => api("/secrets") }); const { toast, openSheet, closeSheet } = useStore();
    return <div className="card"><div className="row" style={{ justifyContent: "space-between" }}><div><h2 className="h-sec" style={{ margin: 0 }}>Secrets</h2><p className="muted" style={{ margin: "4px 0 0" }}>Keys your projects need at deploy time. Injected as environment variables, never written into files.</p></div><Button size="sm" variant="primary" onClick={() => openSheet(<ConnectForm name="" label="secret" kind="env" onDone={() => { closeSheet(); qc.invalidateQueries({ queryKey: ["secrets"] }); toast("Secret saved"); }} />)}>Add secret</Button></div><table className="t" style={{ marginTop: 12 }}><thead><tr><th>Name</th><th>Value</th><th>Kind</th><th></th></tr></thead><tbody>{(data ?? []).filter((s: any) => s.kind !== "deploy_token").map((s: any) => <tr key={s.id}><td><b>{s.name}</b>{s.projectId && <small className="muted"> · project</small>}</td><td><span className="secret">••••••••{s.last4}</span></td><td><Tag>{s.kind}</Tag></td><td style={{ textAlign: "right" }}><Button size="sm" variant="ghost" className="danger" onClick={async () => { await api(`/secrets/${s.id}`, { method: "DELETE" }); qc.invalidateQueries({ queryKey: ["secrets"] }); }}>Delete</Button></td></tr>)}{!data?.length && <tr><td colSpan={4} className="muted">No secrets yet.</td></tr>}</tbody></table></div>; },
  api: () => { const qc = useQueryClient(); const { data } = useQuery({ queryKey: ["apikeys"], queryFn: () => api("/api-keys") }); const { toast, openSheet, closeSheet } = useStore(); const router = useRouter();
    return <div className="card"><h2 className="h-sec">API keys <Tag kind="brand">Studio</Tag></h2><p className="sub">Trigger builds and fetch projects from your own tools.</p>{(data ?? []).map((k: any) => <div key={k.id} className="pm" style={{ cursor: "default" }}><span className="secret">{k.prefix}••••</span><span className="muted">{k.name} · {k.lastUsedAt ? `last used ${new Date(k.lastUsedAt).toLocaleDateString()}` : "never used"}</span><Button size="sm" variant="ghost" className="danger" style={{ marginLeft: "auto" }} onClick={async () => { await api(`/api-keys/${k.id}`, { method: "DELETE" }); qc.invalidateQueries({ queryKey: ["apikeys"] }); }}>Revoke</Button></div>)}<Button size="sm" style={{ marginTop: 10 }} onClick={async () => { try { const r = await api("/api-keys", { method: "POST", json: { name: "Default", scopes: ["projects:read", "projects:write", "builds:run"] } }); qc.invalidateQueries({ queryKey: ["apikeys"] }); openSheet(<><h2 style={{ fontSize: 20 }}>Your new key</h2><p className="sub">Copy it now; it will not be shown again.</p><input className="input secret" readOnly value={r.key} onFocus={(e) => e.target.select()} /><div className="row" style={{ justifyContent: "flex-end", marginTop: 12 }}><Button variant="primary" onClick={() => { navigator.clipboard.writeText(r.key); closeSheet(); toast("Copied"); }}>Copy and close</Button></div></>); } catch (e: any) { if (e.body?.upgrade) router.push("/pricing"); else toast(e.message); } }}>Create key</Button></div>; },
  team: () => { const qc = useQueryClient(); const { data } = useQuery({ queryKey: ["team"], queryFn: () => api("/team") }); const { toast, openSheet, closeSheet } = useStore(); const router = useRouter(); const [email, setEmail] = useState("");
    if (!data) return <div className="card">Loading…</div>; const used = 1 + data.workspace.members.length;
    return <div className="card"><div className="row" style={{ justifyContent: "space-between" }}><h2 className="h-sec" style={{ margin: 0 }}>Team <span className="muted" style={{ fontWeight: 400, fontSize: 13 }}>{used} of {data.seats} seats</span></h2><Button size="sm" variant="primary" onClick={() => openSheet(<><h2 style={{ fontSize: 20 }}>Invite by email</h2><Field label="Email"><input className="input" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} /></Field><div className="row" style={{ justifyContent: "flex-end" }}><Button variant="ghost" onClick={closeSheet}>Cancel</Button><Button variant="primary" onClick={async () => { try { await api("/team/invite", { method: "POST", json: { email } }); closeSheet(); qc.invalidateQueries({ queryKey: ["team"] }); toast("Invite sent"); } catch (e: any) { if (e.body?.upgrade) router.push("/pricing"); else toast(e.message); } }}>Send invite</Button></div></>)}>Invite by email</Button></div><table className="t" style={{ marginTop: 12 }}><thead><tr><th>Member</th><th>Role</th><th>Status</th></tr></thead><tbody><tr><td><b>{data.workspace.owner?.name ?? "You"}</b></td><td>Owner</td><td><Tag kind="ok">Active</Tag></td></tr>{data.workspace.members.map((m: any) => <tr key={m.id}><td>{m.user?.name ?? m.invitedEmail}</td><td>{m.role}</td><td>{m.acceptedAt ? <Tag kind="ok">Active</Tag> : <Tag kind="warn">Invited</Tag>}</td></tr>)}</tbody></table></div>; },
  security: () => { const qc = useQueryClient(); const { data } = useQuery({ queryKey: ["sessions"], queryFn: () => api("/auth/sessions") }); const { user, setUser, toast, openSheet, closeSheet } = useStore(); const router = useRouter();
    async function setup2fa() { const r = await api("/auth/2fa/setup", { method: "POST" }); let code = ""; openSheet(<><h2 style={{ fontSize: 20 }}>Set up two-factor</h2><p className="sub">Add this to your authenticator app, then enter the 6-digit code.</p><input className="input secret" readOnly value={r.otpauth} onFocus={(e) => e.target.select()} /><Field label="Code"><input className="input" inputMode="numeric" autoComplete="one-time-code" onChange={(e) => (code = e.target.value)} /></Field><div className="row" style={{ justifyContent: "flex-end" }}><Button variant="ghost" onClick={closeSheet}>Cancel</Button><Button variant="primary" onClick={async () => { try { const v = await api("/auth/2fa/verify", { method: "POST", json: { code } }); setUser({ ...user, twoFaEnabled: true }); openSheet(<><h2 style={{ fontSize: 20 }}>Recovery codes</h2><p className="sub">Keep these somewhere safe. Each works once.</p><pre className="code">{v.recovery.join("\n")}</pre><Button variant="primary" onClick={closeSheet} style={{ marginTop: 10 }}>Done</Button></>); } catch (e: any) { toast(e.message); } }}>Verify</Button></div></>); }
    return <div className="card"><h2 className="h-sec">Security</h2><div className="pm" style={{ cursor: "default" }}><div><b>Password</b><br /><small className="muted">Managed by your sign-in provider</small></div><Button size="sm" style={{ marginLeft: "auto" }} onClick={async () => { const { resetPassword } = await import("@/lib/firebase"); await resetPassword(user.email); toast("Reset link emailed"); }}>Change</Button></div>
      <div className="pm" style={{ cursor: "default", marginTop: 8 }}><div><b>Two-factor authentication</b><br /><small className="muted">Authenticator app with 10 recovery codes</small></div><Switch on={!!user?.twoFaEnabled} onChange={async (v) => { if (v) setup2fa(); else { await api("/auth/2fa/disable", { method: "POST" }); setUser({ ...user, twoFaEnabled: false }); toast("2FA off"); } }} /></div>
      <h3 style={{ fontSize: 14, margin: "18px 0 8px" }}>Active sessions</h3><table className="t"><tbody>{(data ?? []).map((s: any) => <tr key={s.id}><td>{s.userAgent?.slice(0, 50)} {s.current && <Tag kind="ok">This device</Tag>}</td><td className="muted">{s.ip} · {new Date(s.lastSeenAt).toLocaleString()}</td><td style={{ textAlign: "right" }}>{!s.current && <Button size="sm" variant="ghost" onClick={async () => { await api(`/auth/sessions/${s.id}`, { method: "DELETE" }); qc.invalidateQueries({ queryKey: ["sessions"] }); }}>Sign out</Button>}</td></tr>)}</tbody></table>
      <hr className="sep" /><div className="row wrap"><Button size="sm" onClick={async () => { await api("/auth/signout", { method: "POST", json: { everywhere: true } }); await signOut(auth); router.push("/login"); }}>Sign out everywhere</Button><Button size="sm" onClick={async () => { await api("/account/export", { method: "POST" }); toast("Export ready in a few minutes, check your email"); }}>Download my data</Button><Button size="sm" variant="ghost" className="danger" onClick={() => openSheet(<><h2 style={{ fontSize: 20 }}>Delete your account?</h2><p className="sub">Projects, credits and invoices are deleted. This cannot be undone.</p><div className="row" style={{ justifyContent: "flex-end" }}><Button variant="ghost" onClick={closeSheet}>Keep account</Button><Button variant="danger" onClick={async () => { await api("/auth/delete-account", { method: "POST" }); await signOut(auth); router.push("/login"); }}>Delete</Button></div></>)}>Delete account</Button></div></div>; },
};
function ConnectForm({ name, label, kind = "deploy_token", onDone }: { name: string; label: string; kind?: "deploy_token" | "env" | "api_key"; onDone: () => void }) { const [n, setN] = useState(name); const [v, setV] = useState(""); const { toast } = useStore();
  return <><h2 style={{ fontSize: 20 }}>{name ? `Connect ${label}` : "Add a secret"}</h2>{!name && <Field label="Name"><input className="input" placeholder="STRIPE_SECRET_KEY" value={n} onChange={(e) => setN(e.target.value.toUpperCase())} /></Field>}<Field label={name ? "API token" : "Value"}><input className="input" type="password" autoComplete="off" value={v} onChange={(e) => setV(e.target.value)} /></Field><p className="lock">🔒 Encrypted before it is stored. You will not see it again.</p><div className="row" style={{ justifyContent: "flex-end" }}><Button variant="primary" onClick={async () => { try { await api("/secrets", { method: "POST", json: { name: n, value: v, kind } }); onDone(); } catch (e: any) { toast(e.message); } }}>Save</Button></div></>; }
