"use client";
import { useState } from "react";
import Link from "next/link";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { useStore } from "@/lib/store";
import { Button, Tag, fmt } from "@/components/ui";
const M = [["overview", "Overview"], ["users", "Users"], ["plans", "Plans & packs"], ["models", "Models"], ["prompts", "Prompts"], ["ideas", "Idea cards"], ["jobs", "Jobs"], ["payments", "Payments"], ["deployments", "Deployments"], ["emails", "Emails"], ["flags", "Flags"], ["audit", "Audit"]];
export default function Admin({ params }: { params: { section?: string[] } }) { const sec = params.section?.[0] ?? "overview"; const { user } = useStore();
  if (user && user.role !== "admin") return <div className="page"><div className="card">Admin only.</div></div>;
  if (user && !user.twoFaEnabled) return <div className="page"><div className="card">Turn on two-factor authentication in <Link href="/settings/security">Security</Link> to open the admin console.</div></div>;
  const S = SEC[sec] ?? SEC.overview; return <div className="page"><div className="row wrap" style={{ marginBottom: 18 }}>{M.map(([k, l]) => <Link key={k} className={`ptab ${k === sec ? "on" : ""}`} href={`/admin/${k}`}>{l}</Link>)}</div><S /></div>; }
const $ = (c: number) => `$${(c / 100).toLocaleString("en-US", { minimumFractionDigits: 0 })}`;
const SEC: Record<string, () => JSX.Element> = {
  overview: () => { const { data } = useQuery({ queryKey: ["adm", "overview"], queryFn: () => api("/admin/overview") }); const f = useQuery({ queryKey: ["adm", "funnel"], queryFn: () => api("/admin/analytics/funnel") }); if (!data) return <div className="card">Loading…</div>;
    return <><div className="grid g4"><div className="card kpi"><b>{$(data.revenueCents)}</b><small>Revenue, 30 days</small></div><div className="card kpi"><b>{$(data.providerCostCents)}</b><small>Provider cost</small><span className="d">Margin {data.marginPct}%</span></div><div className="card kpi"><b>{fmt(data.payingUsers)}</b><small>Paying users</small><span className="d">+{data.newUsers} new</span></div><div className="card kpi"><b>{data.failureRatePct}%</b><small>Job failure rate</small><span className="d" style={{ color: data.failureRatePct > 5 ? "var(--bad)" : undefined }}>Alert at 5%</span></div></div>
      <div className="card" style={{ marginTop: 16 }}><h2 className="h-sec">Funnel, 30 days</h2><table className="t"><tbody>{(f.data ?? []).map((s: any) => <tr key={s.stage}><td>{s.stage}</td><td style={{ textAlign: "right" }}><b>{fmt(s.count)}</b></td></tr>)}</tbody></table></div></>; },
  users: () => { const [q, setQ] = useState(""); const qc = useQueryClient(); const { toast } = useStore(); const { data } = useQuery({ queryKey: ["adm", "users", q], queryFn: () => api(`/admin/users?q=${encodeURIComponent(q)}`) });
    return <div className="card"><div className="row" style={{ marginBottom: 10 }}><input className="input" placeholder="Search by email or name" value={q} onChange={(e) => setQ(e.target.value)} style={{ width: 300 }} /></div><table className="t"><thead><tr><th>User</th><th>Plan</th><th>Status</th><th>Joined</th><th></th></tr></thead><tbody>{(data ?? []).map((u: any) => <tr key={u.id}><td><b>{u.email}</b><br /><small className="muted">{u.name}</small></td><td>{u.subscription?.plan?.name ?? "Free"}</td><td><Tag kind={u.subscription?.status === "past_due" ? "warn" : "ok"}>{u.subscription?.status ?? "active"}</Tag></td><td className="muted">{new Date(u.createdAt).toLocaleDateString()}</td><td style={{ textAlign: "right" }}><Button size="sm" variant="ghost" onClick={async () => { const amount = Number(prompt("Credits to grant (negative to remove)")); const note = prompt("Reason") ?? ""; if (!amount || !note) return; await api(`/admin/users/${u.id}/credits`, { method: "POST", json: { amount, note } }); toast("Granted (logged)"); }}>Grant</Button><Button size="sm" variant="ghost" onClick={async () => { const planKey = prompt("Plan key: free, starter, pro, studio"); if (!planKey) return; await api(`/admin/users/${u.id}/plan`, { method: "POST", json: { planKey } }); qc.invalidateQueries({ queryKey: ["adm", "users"] }); }}>Plan</Button><Button size="sm" variant="ghost" className="danger" onClick={async () => { if (!confirm(`Suspend ${u.email}?`)) return; await api(`/admin/users/${u.id}/suspend`, { method: "POST" }); qc.invalidateQueries({ queryKey: ["adm", "users"] }); }}>Suspend</Button></td></tr>)}</tbody></table></div>; },
  plans: () => { const qc = useQueryClient(); const { toast } = useStore(); const { data } = useQuery({ queryKey: ["adm", "plans"], queryFn: () => api("/admin/plans") }); if (!data) return <div className="card">Loading…</div>;
    return <><div className="card"><h2 className="h-sec">Plans</h2><table className="t"><thead><tr><th>Plan</th><th>Price (cents)</th><th>Credits</th><th>Margin at full use</th><th>PayPal plan id</th><th></th></tr></thead><tbody>{data.plans.map((p: any) => <PlanRow key={p.key} p={p} onSave={async (d) => { await api(`/admin/plans/${p.key}`, { method: "PUT", json: d }); qc.invalidateQueries({ queryKey: ["adm", "plans"] }); toast("Saved · pricing page updated"); }} />)}</tbody></table></div>
      <div className="card" style={{ marginTop: 16 }}><h2 className="h-sec">Credit packs</h2><table className="t"><tbody>{data.packs.map((p: any) => <tr key={p.key}><td><b>{p.name}</b></td><td>{fmt(p.credits)} credits</td><td>{$(p.priceCents)}</td><td>+{p.bonusPct}%</td><td><Tag kind={p.active ? "ok" : undefined}>{p.active ? "active" : "off"}</Tag></td></tr>)}</tbody></table></div>
      <div className="card" style={{ marginTop: 16 }}><h2 className="h-sec">Coupons</h2><table className="t"><tbody>{data.coupons.map((c: any) => <tr key={c.code}><td><b>{c.code}</b></td><td>{c.pctOff ? `${c.pctOff}% off` : `+${c.creditsBonus} credits`}</td><td>{c.uses}/{c.maxUses ?? "∞"} used</td></tr>)}</tbody></table><Button size="sm" style={{ marginTop: 10 }} onClick={async () => { const code = prompt("Code"); const pctOff = Number(prompt("Percent off")); if (!code) return; await api(`/admin/coupons/${code.toUpperCase()}`, { method: "PUT", json: { pctOff, active: true } }); qc.invalidateQueries({ queryKey: ["adm", "plans"] }); }}>Add coupon</Button></div></>; },
  models: () => { const qc = useQueryClient(); const { toast } = useStore(); const { data } = useQuery({ queryKey: ["adm", "models"], queryFn: () => api("/admin/models") });
    return <div className="card"><p className="muted">Change provider cost or markup; credits recompute and every estimate in the app updates.</p><table className="t"><thead><tr><th>Model</th><th>Cost in / out per 1k</th><th>Cost per image / s</th><th>Markup</th><th>Credits</th><th>Enabled</th></tr></thead><tbody>{(data ?? []).map((m: any) => <ModelRow key={m.key} m={m} onSave={async (d) => { await api(`/admin/models/${m.key}`, { method: "PUT", json: d }); qc.invalidateQueries({ queryKey: ["adm", "models"] }); toast("Saved"); }} />)}</tbody></table></div>; },
  prompts: () => { const qc = useQueryClient(); const { toast } = useStore(); const { data } = useQuery({ queryKey: ["adm", "prompts"], queryFn: () => api("/admin/prompts") }); const [stage, setStage] = useState("build"); const [content, setContent] = useState(""); const [ab, setAb] = useState(0);
    return <><div className="card"><h2 className="h-sec">Background prompts</h2><p className="muted">Defaults ship in packages/prompts. Versions here override them; an A/B percentage sends that share of builds to the new version.</p><table className="t"><thead><tr><th>Stage</th><th>Version</th><th>Active</th><th>A/B %</th><th>Score</th><th>Created</th></tr></thead><tbody>{(data ?? []).map((p: any) => <tr key={p.id}><td>{p.stage}</td><td>v{p.version}</td><td>{p.active ? <Tag kind="ok">active</Tag> : ""}</td><td>{p.abPct}</td><td>{p.score ?? "—"}</td><td className="muted">{new Date(p.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>
      <div className="card" style={{ marginTop: 16 }}><h2 className="h-sec">New version</h2><div className="row" style={{ marginBottom: 10 }}><select className="input" style={{ width: 160 }} value={stage} onChange={(e) => setStage(e.target.value)}>{["intent", "design", "build", "review", "media"].map((s) => <option key={s}>{s}</option>)}</select><input className="input" type="number" min={0} max={100} style={{ width: 120 }} value={ab} onChange={(e) => setAb(+e.target.value)} placeholder="A/B %" /></div><textarea className="input" rows={12} value={content} onChange={(e) => setContent(e.target.value)} placeholder="Full prompt text for this stage" /><div className="row" style={{ marginTop: 10 }}><Button onClick={async () => { await api("/admin/prompts", { method: "POST", json: { stage, content, abPct: ab } }); qc.invalidateQueries({ queryKey: ["adm", "prompts"] }); toast("Saved as A/B version"); }}>Save for A/B</Button><Button variant="primary" onClick={async () => { await api("/admin/prompts", { method: "POST", json: { stage, content, activate: true } }); qc.invalidateQueries({ queryKey: ["adm", "prompts"] }); toast("Activated"); }}>Save and activate</Button></div></div></>; },
  ideas: () => { const { data } = useQuery({ queryKey: ["adm", "ideas"], queryFn: () => api("/admin/ideas") }); return <div className="card"><h2 className="h-sec">Idea cards</h2><table className="t"><thead><tr><th>Card</th><th>Credits</th><th>Active</th></tr></thead><tbody>{(data ?? []).map((c: any) => <tr key={c.key}><td><b>{c.title}</b><br /><small className="muted">{c.description}</small></td><td>{c.creditEstimate}</td><td><Tag kind={c.active ? "ok" : undefined}>{c.active ? "on" : "off"}</Tag></td></tr>)}</tbody></table></div>; },
  jobs: () => { const qc = useQueryClient(); const { data } = useQuery({ queryKey: ["adm", "jobs"], queryFn: () => api("/admin/jobs"), refetchInterval: 5000 }); return <div className="card"><table className="t"><thead><tr><th>Job</th><th>User</th><th>Project</th><th>Kind</th><th>Status</th><th>Error</th><th></th></tr></thead><tbody>{(data ?? []).map((j: any) => <tr key={j.id}><td className="secret">{j.id.slice(-6)}</td><td>{j.project.workspace.owner.email}</td><td>{j.project.name}</td><td>{j.kind}</td><td><Tag kind={j.status === "done" ? "ok" : j.status === "failed" ? "bad" : "brand"}>{j.status}</Tag></td><td className="muted" style={{ maxWidth: 240, overflow: "hidden", textOverflow: "ellipsis" }}>{j.error}</td><td>{j.status === "failed" && <Button size="sm" variant="ghost" onClick={async () => { await api(`/admin/jobs/${j.id}/retry`, { method: "POST" }); qc.invalidateQueries({ queryKey: ["adm", "jobs"] }); }}>Retry</Button>}</td></tr>)}</tbody></table></div>; },
  payments: () => { const { toast } = useStore(); const { data } = useQuery({ queryKey: ["adm", "payments"], queryFn: () => api("/admin/payments") }); return <div className="card"><table className="t"><thead><tr><th>Event</th><th>User</th><th>Amount</th><th>When</th><th></th></tr></thead><tbody>{(data ?? []).map((p: any) => <tr key={p.id}><td className="secret">{p.eventType}</td><td>{p.user.email}</td><td>{$(p.amountCents)}</td><td className="muted">{new Date(p.createdAt).toLocaleString()}</td><td>{(p.eventType === "capture" || p.eventType === "renewal") && <Button size="sm" variant="ghost" onClick={async () => { if (!confirm("Refund in full?")) return; await api(`/admin/payments/${p.providerId}/refund`, { method: "POST", json: {} }); toast("Refund requested"); }}>Refund</Button>}</td></tr>)}</tbody></table></div>; },
  deployments: () => { const qc = useQueryClient(); const { data } = useQuery({ queryKey: ["adm", "deps"], queryFn: () => api("/admin/deployments") }); return <div className="card"><table className="t"><thead><tr><th>Project</th><th>Provider</th><th>Status</th><th>URL</th><th></th></tr></thead><tbody>{(data ?? []).map((d: any) => <tr key={d.id}><td>{d.project.name}</td><td>{d.provider}</td><td><Tag kind={d.status === "live" ? "ok" : d.status === "failed" ? "bad" : undefined}>{d.status}</Tag></td><td>{d.url && <a href={d.url} target="_blank" rel="noreferrer">{d.url}</a>}</td><td>{d.status === "live" && <Button size="sm" variant="ghost" className="danger" onClick={async () => { await api(`/admin/deployments/${d.id}/takedown`, { method: "POST" }); qc.invalidateQueries({ queryKey: ["adm", "deps"] }); }}>Take down</Button>}</td></tr>)}</tbody></table></div>; },
  emails: () => { const { data } = useQuery({ queryKey: ["adm", "emails"], queryFn: () => api("/admin/emails") }); return <div className="card"><table className="t"><thead><tr><th>Template</th><th>To</th><th>Subject</th><th>Status</th><th>When</th></tr></thead><tbody>{(data ?? []).map((e: any) => <tr key={e.id}><td>{e.template}</td><td>{e.to}</td><td>{e.subject}</td><td><Tag kind={e.status === "sent" ? "ok" : "bad"}>{e.status}</Tag></td><td className="muted">{new Date(e.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>; },
  flags: () => { const qc = useQueryClient(); const { data } = useQuery({ queryKey: ["adm", "flags"], queryFn: () => api("/admin/flags") }); return <div className="card"><h2 className="h-sec">Feature flags</h2><table className="t"><tbody>{(data ?? []).map((f: any) => <tr key={f.key}><td><b>{f.key}</b></td><td>{f.rolloutPct}%</td><td><Button size="sm" onClick={async () => { await api(`/admin/flags/${f.key}`, { method: "PUT", json: { enabled: !f.enabled, rolloutPct: f.rolloutPct } }); qc.invalidateQueries({ queryKey: ["adm", "flags"] }); }}>{f.enabled ? "Disable" : "Enable"}</Button></td></tr>)}</tbody></table><Button size="sm" style={{ marginTop: 10 }} onClick={async () => { const key = prompt("Flag key"); if (!key) return; await api(`/admin/flags/${key}`, { method: "PUT", json: { enabled: false, rolloutPct: 0 } }); qc.invalidateQueries({ queryKey: ["adm", "flags"] }); }}>Add flag</Button></div>; },
  audit: () => { const { data } = useQuery({ queryKey: ["adm", "audit"], queryFn: () => api("/admin/audit") }); return <div className="card"><table className="t"><thead><tr><th>Actor</th><th>Action</th><th>Target</th><th>When</th></tr></thead><tbody>{(data ?? []).map((a: any) => <tr key={a.id}><td>{a.actor?.email ?? "system"}</td><td className="secret">{a.action}</td><td>{a.targetType} {a.targetId?.slice(-6)}</td><td className="muted">{new Date(a.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>; },
};
function PlanRow({ p, onSave }: { p: any; onSave: (d: any) => void }) { const [d, setD] = useState({ priceCents: p.priceCents, creditsPerPeriod: p.creditsPerPeriod, paypalPlanId: p.paypalPlanId ?? "" }); const margin = d.priceCents ? Math.round((1 - (d.creditsPerPeriod * 0.5) / d.priceCents) * 100) : 0;
  return <tr><td><b>{p.name}</b></td><td><input className="input" type="number" value={d.priceCents} onChange={(e) => setD({ ...d, priceCents: +e.target.value })} style={{ width: 100 }} /></td><td><input className="input" type="number" value={d.creditsPerPeriod} onChange={(e) => setD({ ...d, creditsPerPeriod: +e.target.value })} style={{ width: 110 }} /></td><td style={{ color: margin < 50 ? "var(--bad)" : "var(--ok)" }}>{margin}%</td><td><input className="input" value={d.paypalPlanId} onChange={(e) => setD({ ...d, paypalPlanId: e.target.value })} style={{ width: 140 }} /></td><td><Button size="sm" onClick={() => onSave(d)}>Save</Button></td></tr>; }
function ModelRow({ m, onSave }: { m: any; onSave: (d: any) => void }) { const [d, setD] = useState({ costPer1kIn: +m.costPer1kIn, costPer1kOut: +m.costPer1kOut, costPerImage: +m.costPerImage, costPerVideoS: +m.costPerVideoS, markup: +m.markup, enabled: m.enabled });
  return <tr><td><b>{m.label}</b><br /><small className="muted">{m.key}</small></td><td className="row"><input className="input" type="number" step="0.0001" value={d.costPer1kIn} onChange={(e) => setD({ ...d, costPer1kIn: +e.target.value })} style={{ width: 90 }} /><input className="input" type="number" step="0.0001" value={d.costPer1kOut} onChange={(e) => setD({ ...d, costPer1kOut: +e.target.value })} style={{ width: 90 }} /></td><td className="row"><input className="input" type="number" step="0.01" value={d.costPerImage} onChange={(e) => setD({ ...d, costPerImage: +e.target.value })} style={{ width: 80 }} /><input className="input" type="number" step="0.01" value={d.costPerVideoS} onChange={(e) => setD({ ...d, costPerVideoS: +e.target.value })} style={{ width: 80 }} /></td><td><input className="input" type="number" step="0.1" value={d.markup} onChange={(e) => setD({ ...d, markup: +e.target.value })} style={{ width: 70 }} /></td><td className="muted">{m.creditsPerImage ? `${m.creditsPerImage}/img` : m.creditsPerVideoS ? `${m.creditsPerVideoS}/s` : `${(+m.creditsPer1kIn).toFixed(2)} / ${(+m.creditsPer1kOut).toFixed(2)} per 1k`}</td><td><Button size="sm" onClick={() => onSave(d)}>Save</Button> <Button size="sm" variant="ghost" onClick={() => onSave({ enabled: !m.enabled })}>{m.enabled ? "Disable" : "Enable"}</Button></td></tr>; }
