"use client";
import { useState } from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { useStore } from "@/lib/store";
import { fmt } from "@/components/ui";
export default function Pricing() { const [yearly, setYearly] = useState(false); const { data } = useQuery({ queryKey: ["catalog"], queryFn: () => api("/billing/catalog") }); const { user } = useStore(); const bill = useQuery({ queryKey: ["billing"], queryFn: () => api("/billing"), enabled: !!user });
  const cur = bill.data?.subscription?.planKey ?? (user ? "free" : null);
  return <div className="page"><div style={{ textAlign: "center" }}><h1 style={{ fontSize: 34, letterSpacing: "-.02em" }}>Plans that pay for themselves</h1><p className="sub" style={{ fontSize: 16 }}>Credits turn into websites, apps, images and videos. Pro is about 30 full websites a month.</p><div className="toggle"><button className={!yearly ? "on" : ""} onClick={() => setYearly(false)}>Monthly</button><button className={yearly ? "on" : ""} onClick={() => setYearly(true)}>Yearly · 2 months free</button></div></div>
    <div className="plans">{(data?.plans ?? []).map((p: any) => { const pr = p.priceCents / 100; return <div key={p.key} className={`plan ${p.key === "pro" ? "hot" : ""}`}>{p.key === "pro" && <span className="pop">Most popular</span>}<b>{p.name}</b><div className="price">${yearly ? Math.round(pr * 10 / 12) : pr}<small>/month{yearly && pr ? " billed yearly" : ""}</small></div><div className="muted">{fmt(p.creditsPerPeriod)} credits{p.key === "free" ? " one-time" : " / month"}</div><ul><li>{p.maxProjects ? `${p.maxProjects} projects` : "Unlimited projects"}</li>{p.maxTeamMembers > 1 && <li>{p.maxTeamMembers} team seats</li>}{p.features.map((f: string) => <li key={f}>{f}</li>)}</ul>
      <Link className={`btn ${p.key === "pro" ? "primary" : ""}`} style={{ marginTop: "auto" }} href={cur === p.key ? "/settings/billing" : pr ? `/checkout?plan=${p.key}${yearly ? "&yearly=1" : ""}` : user ? "/" : "/login"}>{cur === p.key ? "Current plan" : pr ? `Choose ${p.name}` : "Start free"}</Link></div>; })}</div>
    <div className="grid g3" style={{ marginTop: 28 }}><div className="card flat"><b>What costs what</b><p className="muted" style={{ margin: "6px 0 0" }}>Website 60–150 · Web app with admin 150–400 · Image 8 · 10 s video 800. The exact cost shows before every run.</p></div><div className="card flat"><b>Need more?</b><p className="muted" style={{ margin: "6px 0 0" }}>Credit packs from $10, bigger packs carry up to 25% bonus and never expire on paid plans.</p></div><div className="card flat"><b>Cancel anytime</b><p className="muted" style={{ margin: "6px 0 0" }}>Your projects and source code stay yours forever, on any plan.</p></div></div></div>; }
